SELECT A1.PRODUCT_CODE, SUM(A1.PRICE * A2.SALES_AMOUNT) AS SALES
FROM PRODUCT A1
LEFT OUTER JOIN OFFLINE_SALE A2
ON A1.PRODUCT_ID = A2.PRODUCT_ID
GROUP BY A1.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC