SELECT P.PRODUCT_CODE PRODUCT_CODE, SUM(P.PRICE * OS.SALES_AMOUNT) SALES
FROM PRODUCT P 
INNER JOIN OFFLINE_SALE OS
ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC